# Generated by Django 4.1 on 2022-09-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_title_service_service_delete_availability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Facility',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='service',
            new_name='title',
        ),
    ]
